apiVersion: v1
kind: Service
metadata:
  name: clickhouse
spec:
  selector:
    app: clickhouse
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 9000
      nodePort: 30036
      protocol: TCP