apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: clickhouse
  namespace: my-app
spec:
  selector:
    matchLabels:
      app: clickhouse
  template:
    metadata:
      labels:
        app: clickhouse
    spec:
      containers:
      - name: clickhouse
        image: clickhouse/clickhouse-server:21.8
        volumeMounts:
        - name: clickhouse-data
          mountPath: /var/lib/clickhouse
        ports:
        - containerPort: 9000
  volumeClaimTemplates:
  - metadata:
      name: clickhouse-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi